stages:
- name: Build
  steps:
    - runScriptConfig:
        image: maven:3-jdk-8
        shellScript: mvn clean package
- name: Publish
  steps:
    - publishImageConfig:
        dockerfilePath: ./Dockerfile
        buildContext: .
#        tag: fullj/pipeline-example-spring:${CICD_EXECUTION_SEQUENCE}
        tag: fullj/pipeline-example-spring:${CICD_GIT_BRANCH}
        pushRemote: true
        registry: harbor.mihoyo.com
      env:
        PLUGIN_DEBUG: true
- name: Deploy
  steps:
    - applyYamlConfig:
        path: ./deployment.yml

timeout: 60000
